- README.md
Fix Travis build status icon and link to point to the `.com` version of Travis, instead of the `.org`.
> Fix Travis build status icon and link

- CHANGELOG.md
- src/Connector.php
- src/Powerdns.php
- src/Transformers/RRSetTransformer.php
Release version 1.0.1 of this package.
fixes #11 
fixes #12 
```
[Compare v1.0.0 - v1.0.1](https://github.com/exonet/powerdns-php/compare/v1.0.0...v1.0.1)
- The `Content-Type` header is now also set when making calls to the API. ([#11](https://github.com/exonet/powerdns-php/issues/11))
- Changed the payload key from `set_ptr` to the correct `set-ptr` in the RRSetTransformer. ([#12](https://github.com/exonet/powerdns-php/issues/12))
```
> Release 1.0.1

- src/AbstractZone.php
- src/Powerdns.php
- tests/PowerdnsTest.php
- tests/ZoneTest.php
Feature enhancement: list domains to support bulk operations.
new method:
```
$powerdns->listZones: Zone[];
```
Once working with Zone[], knowing what zone is being returned is helpful for consuming code.
```
$zone->getCanonicalName(): string;
```
> Enhancement: Add support to list zones

- src/Transformers/Nsec3paramTransformer.php
- src/Zone.php
Changes to the `Zone` class to allow nsec3param entries to be set.
I added a `put` function inside the `Zone` class. This is the generic put method for a Zone object.
I added a `setNsec3param` function inside the `Zone` class to set NSEC3PARMS
I modified the `setDnssec` function to use the new put method
fixes #25 
This has been tested on our sandbox environment
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests …
> (GH-25) Allow nsec3param entries to be added

- CHANGELOG.md
- src/Resources/Zone.php
- tests/Resources/ZoneTest.php
Improve NSEC3PARAM validation and prepare new release.
More info about the parameters: https://doc.powerdns.com/authoritative/dnssec/operational.html#setting-the-nsec-modes-and-parameters.
> Improve NSEC3PARAM validation

- src/RecordType.php
> Add SPF record type

- CHANGELOG.md
- composer.json
- src/Powerdns.php
- tests/PowerdnsTest.php
Extended https://github.com/exonet/powerdns-php/pull/45 to support statistics parameters available in PowerDNS 4.3.
Original Pull Request👇
--------
Allow to fetch PowerDNS internal statistics:
https://doc.powerdns.com/authoritative/http-api/statistics.html
I would like to be able to extract statistics with this library.
Tested with real PowerDNS instance.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests …
> Get PowerDNS statistics

- src/Powerdns.php
- tests/PowerdnsTest.php
Allow to fetch PowerDNS internal statistics:
https://doc.powerdns.com/authoritative/http-api/statistics.html
I would like to be able to extract statistics with this library.
Tested with real PowerDNS instance.
> Allow to return statistics endpoint data

- CHANGELOG.md
- src/Transformers/CreateZoneTransformer.php
- tests/functional/AdvancedZoneCreationTest.php
Save the DNS zone account.
The `account` was not saved to PowerDNS, it is now.
Why is this change required? What problem does it solve?
fixes #47 
Updated the included test.
> Fix providing account-value on new zone

- src/Connector.php
- src/Zone.php
When you have a DNS setup with slaves, you may want to notify the slaves manually. PowerDNS API has a call for it, but it wasn't implemented in this package.
See https://doc.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id-notify for the call specification
The changes made to make this work are a new method called `notify` in `src/Zone.php` and the argument for the transformer in the method `put` in `src/Connector.php` has a default value of null. As shown in the PowerDNS API documentation, the no payload must be send.
As said in the description. When you have a setup with slaves, you may want to notify them manually if this isn't done automatically. 
After for example a new zone is created call `$powerdns->zone($domain)->notify();` and see if the slaves …
> Added support for PowerDNS API notify call

- src/Powerdns.php
- tests/PowerdnsTest.php
Performance improvement for PowerDns::listZones
By adding support to include `dnssec` query parameter when calling `/servers/{server_id}/zones` you can set this to false to speed up the performance. With 12000 zones for example the time goes from ±8.8 seconds to ±0.9 seconds.
See linked issue #60.
The unit test for listZones is changed to test the behaviour.
When comparing the results for dnssec query parameter set to `true` and `false` I couldn't see any difference with my local setup. My knowledge of PowerDNS is limited. So perhaps you can see a differents in the result from PowerDNS API.
N/A
Please, please, please, don't …
> Added support for /servers/{server_id}/zones query parameter dnssec in PowerDns::listZones

- CHANGELOG.md
- run-tests.sh
- src/Resources/Zone.php
- src/Zone.php
- tests/Resources/ZoneTest.php
- tests/ZoneTest.php
This PR changes (non-breaking) the signature of `setNsec3Param` to allow unsetting the nsec3param for a zone.
Zones without DNSSEC do not support nsec3param, so it needs to be unset.
Unit test has been created, and test it against our dummy DNS.
> Allow unsetting nsec3param

- CHANGELOG.md
- composer.json
- examples/new_domain_from_zone_resource.php
- run-tests.sh
- src/Helper.php
- src/Resources/Zone.php
- src/Transformers/CreateZoneTransformer.php
- src/Zone.php
- tests/HelperTest.php
- tests/ZoneTest.php
- tests/functional/AdvancedZoneCreationTest.php
- tests/functional/FunctionalTestCase.php
- tests/functional/GitHub38Test.php
- tests/functional/ValidateSOAIncrementTest.php
- tests/functional/ZoneRecordsTest.php
- tests/functional/ZoneTest.php
It is now possible to set/get resource records to a zone resource. See the `examples/new_domain_from_zone_resource.php` example.
> Add resource records when creating a new zone

- .docker/powerdns44/pdns.conf
- docker-compose.yml
- run-tests.sh
Extended the docker-compose.yml for PowerDNS 4.4
The docker hub https://hub.docker.com/r/psitrax/powerdns does not have a tag for PowerDNS 4.4, but the tag `latest` has the correct version. 
The pdns.conf is different in 4.4. The fields `default-soa-name` and `default-soa-email` are removed and replaced by `default-soa-content`.
It is best to use the tag 4.4 when it becomes available. For now this will at least prove that the code works for PowerDNS 4.4.
I would love to have support for PowerDNS 4.4
fixes #66 
By running `run-tests.sh`
Please, please, please, don't send your pull request until all of the boxes are ticked. …
> Added docker service for PowerDNS 4.4

- src/Powerdns.php
- src/PowerdnsInterface.php
This changes the default port to 8081, the default port used by [PowerDNS](https://doc.powerdns.com/authoritative/http-api/index.html#webserver)
When this library was first created, the [docs](https://github.com/PowerDNS/pdns/pull/7464) of powerdns referenced the wrong port, it is time to correct this in the library as well :-)
Closes #84 
Fixes #36 
If you're unsure about any of …
> Update default port to 8081

- examples/list_records_for_zone.php
Renamed variables to something that makes more sense.
Variable names used in example were confusing.
> Use variables that make sense in examples

- .travis.yml
When running tests on Travis; login to Docker to bypass Docker rate limit.
> Login to docker before pulling containers

- src/Zone.php
- tests/ZoneTest.php
Fix undefined exception when passing empty array.
Unit test has been added
> Fix undefined variable exception

- src/Transformers/SoaEditApiTransformer.php
- src/Transformers/SoaEditTransformer.php
- src/Zone.php
Added the setSoaEdit and setSoaEditApi methods to the Zone class to be able to set the soa_edit and soa_edit_api domain metadata.
Doesn't fix an open issue, just adding an extra feature
New methods tested on a live PowerDNS server v4.6
> Add `setSoaEdit` and `setSoaEditApi` methods to Zone class

- composer.json
Add additional `psr/log` versions to composer so the library is compabible with projects using newer `psr/log` version. Details as in https://github.com/exonet/powerdns-php/issues/109
It's impossible to use the library in projects with `psr/log` other than `^1.0`. That excludes almost all modern projects with `psr/log` 3.0.
The existing tests pass.
Changes between `psr/log` major versions 1.0, 2.0 and 3.0 don't change the public interface but only add type hints according to minimal PHP versions for `psr/log` . The `powerdns-php` is using logger interface properly, so it doesn't require any code updates.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull …
> #109 Make package compatible with psr/log 3.0

- src/Resources/ResourceRecord.php
Get only the subdomain from the ResourceRecord object.
Get only the subdomain part from the ResourceRecord object
This method creates an easy way to get only the subdomain part from the ResourceRecord. Handy in situations where the domain part is obvious or unnecessary.
Tested by using it in our project.
If you're unsure about any of these, don't hesitate to ask. We're here to …
> Added getShortName() method

- src/Powerdns.php
- src/Resources/Zone.php
- src/Transformers/KindTransformer.php
- src/Zone.php
- tests/ZoneTest.php
To automate moving zones to PowerDNS we make them Slave first and later change them to Master.
This library could not do that yet, so I have implemented it.
- Added unit test
- All Github Actions are green.
- Changed Master->Slave and Slave->Master on live PowerDNS 4.7.3
> Change the kind of zone

- src/Zone.php
Accept non-canonical zone name in find. Fixes #126.
> Accept non-canonical zone name in find

- examples/new_slave_domain.php
- src/Powerdns.php
Added an example how to add a slave domain.
It is not hard but it took me quite a while to find out exactly how to do it.
Tested on a live PowerDNS 4.7.3
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
> Added example how to add a slave domain

- src/Powerdns.php
- src/PowerdnsInterface.php
Change `$omitDnssecAndEditedSerialFields` to `$includeDnssecAndEditedSerialFields`. The functionality remains the same.
Resolves #134.
> Change parameter `$omitDnssecAndEditedSerialFields` to `$includeDnssecAndEditedSerialFields`

- src/Helper.php
- src/Transformers/CommentTransformer.php
- src/Transformers/RRSetTransformer.php
- src/Zone.php
- tests/HelperTest.php
- tests/Resources/CommentTest.php
- tests/functional/ZoneRecordsTest.php
Hello, while testing i realized that the code-side of updating/adding comments is there, just missing in the transformers for the actual request. This PR adds the functionality and should work as expected.
Relevant docs: https://doc.powerdns.com/authoritative/http-api/zone.html#rrset
Well
./run-test script runs through no problem, changing my local development env to my github repo and adding/updating comments updates them accordingly
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our …
> fix: RRSet save comments

- README.md
- src/Powerdns.php
- src/Resources/ResourceRecord.php
- src/Zone.php
- tests/ZoneTest.php
As proposed in this discussion: https://github.com/exonet/powerdns-php/discussions/146 here would be an implementation for the mentioned.
Keeping track of what parameters to give to the `create` method can get complicated. By enabling the developer to pass Objects we enable a cleaner syntax + enable the usage of auto-complete and other IDE features.
tests are passing, I have tested on 8.1 in my dev-env
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests …
> Support passing `ResourceRecord` objects when creating new records

- src/Resources/Zone.php
- tests/Resources/ZoneTest.php
- tests/ZoneTest.php
`$powerdns->zone($domain)->unsetNsec3param()`  
This wasn't working because `{"nsec3param": null}` was passed in API.  
Now, modified to pass `{"nsec3param": ""}` in API to unset nsec3param.
php: 8.2
powerdns version: 4.9.1-1pdns.buster
All phpunit test cases passed: `./vendor/bin/phpunit`
> fix(nsec3): fixes unset nsec3param not working

- src/Powerdns.php
- src/Resources/Zone.php
- tests/Resources/ZoneTest.php
the `#setNameservers` method will accept any input, while powerdns only accept canonical nameservers (ending in `.`). With the PR, the dot will be automatically appended if it's missing.
Automatically settings this resolve an issue i'm having with customer not setting the appending dot.
tests were fitted
> feat: make nameservers auto canoncial

- .gitattributes
- examples/cryptokeys_advanced.php
- tests/PowerdnsTest.php
- tests/Resources/ResourceRecordTest.php
Add a `.gitattributes` file that defines which files to exclude in when running `git archive`.
When composer-installing this package now only the following files are downloaded:
- src/
- composer.json
- LICENSE.md
- README.md
More info on export-ignore via gitattributes: https://git-scm.com/docs/gitattributes#_export_ignore
This reduces the size of the package when installing via composer. Files that are not needed to run the package in another project are no longer included. For example the tests.
Run `git archive -o latest.zip HEAD` and see the zip archive no longer contains things like tests.
- ~I have added tests to cover my changes.~
> Define git archive excluded files

- src/Transformers/ApiRectifyTransformer.php
- src/Zone.php
basically added enableApiRectify() and disableApiRectify() in order to be able to set this parameter for a zone.
While api_rectify is present as a readonly value for the zones, there is no method to set this parameter.
called $powerdns->zone($domain)->enableApiRectify();
and $powerdns->zone($domain)->disableApiRectify();
verified changes on powerdns-server - as it is quite trivial - this got it approved internally.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests …
> add api_rectify handling for zones

- src/Resources/Zone.php
Remove not-working iterations check. Iteration 0 is valid. This check was not working due to strict-compare between string and int always returning false
Even when providing 0 as iteration it was comparing `'0' === 0`. Because this is a strict-compare, it always returns false.
It removes code that looks like it should prevent using 0 as iteration while in reality this was not the case. 
All tests ran and pass. Some testcases use 0 as iteration and they still are passing.
> Remove not-working iterations check
