CHANGELOG.md
src/AbstractZone.php

Prepare v1.1.0 release

---

CHANGELOG.md
examples/list_records_for_zone.php
examples/new_domain_from_zone_resource.php
src/Powerdns.php
src/Transformers/CreateZoneTransformer.php
tests/functional/AdvancedZoneCreationTest.php
tests/functional/ValidateSOAIncrementTest.php

Create a new zone based on a zone resource, allowing more advanced zone configuration on creation.
Closes #21 and adds the example created in #22.

Create zone from resource

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
src/RecordType.php

Release updated record types.
```
[Compare v2.2.0 - v2.3.0](https://github.com/exonet/powerdns-php/compare/v2.2.0...v2.3.0)
- The record type `SPF`. ([Th3Mouk](https://github.com/Th3Mouk) - [#30](https://github.com/exonet/powerdns-php/pull/30))
- Removed record types `APL`, `HIP` and `TA` which are not supported by PowerDNS.
```

Update record types

---

.travis.yml
.travis/install-pdns.sh
.travis/pdns-43.sql
CHANGELOG.md
src/Connector.php

```
- No longer throw an exception when throwing an exception if the response body is not an error. (#32)
```
Closes #32

Prevent exception when throwing exception

---

src/RecordType.php

Add support for LUA records
https://doc.powerdns.com/authoritative/lua-records/index.html#
This is only const

Add support for LUA records

---

.travis.yml
composer.json
run-tests.sh

Adding support for PHP 8
Installing the package on an environment with PHP 8
With `run_tests.sh` helper 

Add support for PHP 8

---

CHANGELOG.md
src/Connector.php
src/Powerdns.php
src/Resources/SearchResult.php
src/Resources/SearchResultSet.php
src/Zone.php
tests/PowerdnsTest.php
tests/ZoneTest.php
tests/functional/ValidateSOAIncrementTest.php

Add the search endpoint to the package and prepare new release.

Add PowerDNS Search

---

.gitignore
.travis.yml
CHANGELOG.md
composer.json
phpunit.xml
run-tests.sh
src/Connector.php

Update dependencies and remove support for unsupported PHP versions. This will implement and close #50.

Update dependencies and deprecate unsupported PHP versions

---

CHANGELOG.md
src/Powerdns.php

Prepare release v3.1.0

---

CHANGELOG.md
src/Powerdns.php

Update versions for release 3.2.0.

Update versions for release 3.2.0

---

CHANGELOG.md
src/Powerdns.php

Prepare release for 3.3.0

---

CHANGELOG.md
docker-compose.yml
src/Connector.php

Replace deprecated Guzzle function. See #75.

Replace deprecated Guzzle function

---

README.md

Fix the travis-ci link in the README

Fix the travis-ci link in the README

---

.github/workflows/draft-release.yaml

Automatically update the client version after a push to master

Automatically update the client version after a push to master

---

examples/BasicAuthConnector.php
examples/custom_connector.php

Add custom connector example

---

src/Resources/ResourceRecord.php

Remove debug variables

---

examples/manage_meta.php
src/Exceptions/InvalidMetaKind.php
src/Exceptions/ReadOnlyException.php
src/Meta.php
src/MetaType.php
src/Resources/Meta.php
src/Resources/MetaSet.php
src/Transformers/MetaTransformer.php
src/Zone.php
tests/functional/MetaTest.php

Add initial support for managing zone meta data. 
Resolves #132.

Add initial support for managing zone meta data

---

src/Helper.php
tests/HelperTest.php

Prevent notice if no comments are passed.

Prevent notice if no comments are passed

---

.github/workflows/tests.yaml
run-tests.sh

Add PHP 8.3

---

.github/workflows/tests.yaml
docker-compose.yml
run-tests.sh

Update PowerDNS versions for tests.

Update PowerDNS versions for tests
